modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "foxified_library"
version = "${version}"
displayName = "FoxifiedLibrary"
authors = "ThinkingStudio, TexTrue"
description = '''

'''
#logoFile = ""

[[dependencies.foxified_library]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foxified_library]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "example_mod.mixins.json"
